# Generated by Django 5.1.3 on 2024-12-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount_value'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_from',
            field=models.DateField(verbose_name='Valid_from'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateField(verbose_name='Valid_to'),
        ),
    ]
