# Generated by Django 5.1.3 on 2024-12-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_discount_discount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateField(),
        ),
    ]
